---
title: "Netflix’s TuDum Top 10"
format: html
execute: 
  echo: true
  warning: false
  message: false
---

```{r}
#Load Packages

if(!require("tidyverse")) install.packages("tidyverse")
library(readr)
library(dplyr)
library(stringr)
library(DT)

#Acquire Data

if(!dir.exists(file.path("data", "mp01"))){
    dir.create(file.path("data", "mp01"), showWarnings=FALSE, recursive=TRUE)
}

GLOBAL_TOP_10_FILENAME <- file.path("data", "mp01", "global_top10_alltime.csv")

if(!file.exists(GLOBAL_TOP_10_FILENAME)){
    download.file("https://www.netflix.com/tudum/top10/data/all-weeks-global.tsv", 
                  destfile=GLOBAL_TOP_10_FILENAME)
}

COUNTRY_TOP_10_FILENAME <- file.path("data", "mp01", "country_top10_alltime.csv")

if(!file.exists(COUNTRY_TOP_10_FILENAME)){
    download.file("https://www.netflix.com/tudum/top10/data/all-weeks-countries.tsv", 
                  destfile=COUNTRY_TOP_10_FILENAME)
}

#Read files

GLOBAL_TOP_10 <- read_tsv(
  GLOBAL_TOP_10_FILENAME, na = "N/A", show_col_types = FALSE)

str(GLOBAL_TOP_10)


COUNTRY_TOP_10 <- read_tsv(
  COUNTRY_TOP_10_FILENAME,na = "N/A", show_col_types = FALSE)

str(COUNTRY_TOP_10)

#Formatted


format_titles <- function(df){
    colnames(df) <- str_replace_all(colnames(df), "_", " ") |> str_to_title()
    df
}

#Data Tables


GLOBAL_TOP_10 |> 
    mutate(`runtime_(minutes)` = round(60 * runtime)) |>
    select(-season_title, 
           -runtime) |>
    format_titles() |>
    head(n=20) |>
    datatable(options=list(searching=FALSE, info=FALSE)) |>
    formatRound(c('Weekly Hours Viewed', 'Weekly Views'))

COUNTRY_TOP_10 |> 
    select(-season_title, -country_iso2) |>
    format_titles() |>
    head(n=20) |>
    datatable(options=list(searching=FALSE, info=FALSE)) 

```

```{r}
#Exploratory Questions

#Q1
countries_n <- COUNTRY_TOP_10 |>
  summarize(n_countries = n_distinct(country_name))
countries_n

```
Netflix appears to operate in `r countries_n$n_countries` countries around the world.








